# Generated by Django 3.0.5 on 2020-04-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('opening', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('adj_close', models.FloatField()),
            ],
        ),
    ]
